---

- name: install base packages
  apt:
    pkg: "{{ item.name }}"
    state: '{{item.state|default("installed")}}'
    purge: '{{item.purge|default(true)}}'
    install_recommends: no
    cache_valid_time: 3600
  with_items:
    base_packages
  when: base_packages is defined

- name: install base extra packages
  apt:
    pkg: "{{ item.name }}"
    state: '{{item.state|default("installed")}}'
    purge: '{{item.purge|default(true)}}'
    install_recommends: no
    cache_valid_time: 3600
  with_items:
    base_extra_packages
  when: base_extra_packages is defined
